### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by stanislav-web** [yegor-pelykh/KunaAPI#1]
Refactor please 

`
(node:50788) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:50788) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:50788) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
`

**Environment:**

NodeJs: 10.16.0 LTS (Win32)

**Comment by yegor-pelykh** [comment]
There is a new version 0.0.6, it should fix these warnings.

48ab8ffdaf5bd3a63e4d71d5e273fa74a60eeebb

Could you check please?

**Comment by stanislav-web** [comment]
Hi! Thank you ! It looks like better
